//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Zerohunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collection_requests()
        {
            this.employee_assignments = new HashSet<employee_assignments>();
        }
    
        public int collection_request_id { get; set; }
        public int restaurant_id { get; set; }
        public System.DateTime request_date { get; set; }
        public int maximum_preservation_time { get; set; }
        public string assignEmp { get; set; }
    
        public virtual restaurant restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_assignments> employee_assignments { get; set; }
    }
}
