//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Zerohunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_items
    {
        public int food_item_id { get; set; }
        public int collection_request_id { get; set; }
        public string food_type { get; set; }
        public int quantity { get; set; }
    
        public virtual collection_requests collection_requests { get; set; }
    }
}
