//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Zerohunger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerNGOEntities : DbContext
    {
        public ZeroHungerNGOEntities()
            : base("name=ZeroHungerNGOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<collection_requests> collection_requests { get; set; }
        public virtual DbSet<employee_assignments> employee_assignments { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<food_items> food_items { get; set; }
        public virtual DbSet<restaurant> restaurants { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<admin> admins { get; set; }
    }
}
