//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO_Zerohunger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant_food
    {
        public int id { get; set; }
        public int restaurant_id { get; set; }
        public int quantity { get; set; }
        public string food_name { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
